version: '3'

services:
  shell2http:
    build: .
#    image: docker.korniychuk.pro/shell2http-with-docker
    command:
      - "/"
      - "/deploy/deploy.sh"
    ports:
      - 8000:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ".:/deploy"
